//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgilFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Users = new HashSet<Users>();
        }
    
        public string branch_name { get; set; }
        public string branch_address { get; set; }
        public int branch_postal_code { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
