//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgilFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionality
    {
        public Funcionality()
        {
            this.Role = new HashSet<Role>();
        }
    
        public string func_name { get; set; }
        public int func_id { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
    }
}
