//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgilFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Funcionality = new HashSet<Funcionality>();
        }
    
        public string role_name { get; set; }
        public bool role_active { get; set; }
        public int role_id { get; set; }
    
        public virtual ICollection<Funcionality> Funcionality { get; set; }
    }
}
