//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgilFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Branch = new HashSet<Branch>();
            this.Role = new HashSet<Role>();
        }
    
        public string user_username { get; set; }
        public string user_password { get; set; }
    
        public virtual ICollection<Branch> Branch { get; set; }
        public virtual ICollection<Role> Role { get; set; }
    }
}
